fix

diff --git a/.github/workflows/aquilax-scan.yml b/.github/workflows/aquilax-scan.yml
--- a/.github/workflows/aquilax-scan.yml
+++ b/.github/workflows/aquilax-scan.yml
@@ -32,53 +32,54 @@ jobs:
           AQUILAX_AUTH: ${{ secrets.AQUILAX_API_TOKEN }}
         run: |
           scan_info=$(aquilax scan --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --git-uri "https://github.com/AquilaX-AI/vulnapp-python" --scanners "sast_scanner" "iac_scanner" --public True --frequency Once --tags "cicd" "audit")
-          echo "$scan_info" | jq .
+          echo "$scan_info" | jq
           SCAN_ID=$(echo "$scan_info" | jq -r '.scan_id')
           PROJECT_ID=$(echo "$scan_info" | jq -r '.project_id')
           echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
           echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
 
       - name: Poll for Scan Completion
+        env:
+          AQUILAX_AUTH: ${{ secrets.AQUILAX_API_TOKEN }}
         run: |
           while true; do
-            scan_status=$(aquilax get-scan-details --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --project-id "$PROJECT_ID" --scan-id "$SCAN_ID" 2>&1)
-            
-            # Output scan status for debugging
-            echo "Scan Status Output: $scan_status"
-
-            # Check if response is a valid JSON
-            if echo "$scan_status" | jq . >/dev/null 2>&1; then
-              status=$(echo "$scan_status" | jq -r '.scan.status')
-              if [ "$status" = "COMPLETED" ]; then
-                echo "Scan completed!"
-                break
-              else
-                echo "Scan status: $status. Waiting for 30 seconds..."
-              fi
+            scan_status=$(aquilax get-scan-details --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --project-id "$PROJECT_ID" --scan-id "$SCAN_ID")
+            echo "$scan_status" | jq
+            status=$(echo "$scan_status" | jq -r '.scan.status')
+            if [ "$status" = "COMPLETED" ]; then
+              echo "Scan completed!"
+              break
             else
-              echo "Error: Invalid JSON response. Retrying in 30 seconds..."
+              echo "Scan status: $status. Waiting for 30 seconds..."
+              sleep 30
             fi
-            sleep 30
           done
 
-      - name: Save Scan Results
+      - name: Check for Vulnerabilities
+        id: check_vulns
+        env:
+          AQUILAX_AUTH: ${{ secrets.AQUILAX_API_TOKEN }}
         run: |
-          scan_results=$(aquilax get-scan-details --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --project-id "$PROJECT_ID" --scan-id "$SCAN_ID")
-          echo "$scan_results" > scan_results.json
+          scan_status=$(aquilax get-scan-details --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --project-id "$PROJECT_ID" --scan-id "$SCAN_ID")
+          echo "$scan_status" > scan_results.json
+          cat scan_results.json
+          
+          # Check for vulnerabilities
+          vulns=$(jq -r '.scan.results[] | select(.findings != null) | .findings[]' scan_results.json)
+          if [[ -n "$vulns" ]]; then
+            echo "Vulnerabilities found!"
+            if [[ "${{ secrets.FAIL_ON_VULNS }}" == "true" ]]; then
+              echo "Failing the pipeline due to vulnerabilities..."
+              exit 1
+            else
+              echo "Continuing despite vulnerabilities..."
+            fi
+          else
+            echo "No vulnerabilities found."
+          fi
 
       - name: Upload Scan Results
         uses: actions/upload-artifact@v2
         with:
           name: aquilax-scan-results
           path: scan_results.json
-
-      - name: Check for Vulnerabilities
-        run: |
-          vulns=$(jq -r '.scan.results[] | select(.findings != null) | .findings[]' scan_results.json)
-          if [[ -n "$vulns" ]]; then
-            vuln_count=$(echo "$vulns" | wc -l)
-            echo "$vuln_count vulnerabilities found!"
-            exit 1
-          else
-            echo "No vulnerabilities found."
-          fi
