test

diff --git a/.github/workflows/aquilax-scan.yml b/.github/workflows/aquilax-scan.yml
--- a/.github/workflows/aquilax-scan.yml
+++ b/.github/workflows/aquilax-scan.yml
@@ -32,11 +32,19 @@ jobs:
           AQUILAX_AUTH: ${{ secrets.AQUILAX_API_TOKEN }}
         run: |
           scan_info=$(aquilax scan --org-id "6691108b1985981c1f5d5b93" --group-id "66cc51d790da713a3f7c6075" --git-uri "https://github.com/AquilaX-AI/vulnapp-python" --scanners "sast_scanner" "iac_scanner" --public True --frequency Once --tags "cicd" "audit")
-          echo "$scan_info" | jq
+          echo "Scan Info: $scan_info"
+          # Extract SCAN_ID and PROJECT_ID
           SCAN_ID=$(echo "$scan_info" | jq -r '.scan_id')
           PROJECT_ID=$(echo "$scan_info" | jq -r '.project_id')
+
+          if [[ -z "$SCAN_ID" || -z "$PROJECT_ID" ]]; then
+            echo "Failed to extract SCAN_ID or PROJECT_ID"
+            exit 1
+          fi
+
           echo "SCAN_ID=$SCAN_ID" >> $GITHUB_ENV
           echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
+          echo "Scan started with SCAN_ID=$SCAN_ID and PROJECT_ID=$PROJECT_ID"
 
       - name: Poll for Scan Completion
         env:
@@ -49,6 +57,9 @@ jobs:
             if [ "$status" = "COMPLETED" ]; then
               echo "Scan completed!"
               break
+            elif [ "$status" = "FAILED" ]; then
+              echo "Scan failed!"
+              exit 1
             else
               echo "Scan status: $status. Waiting for 30 seconds..."
               sleep 30
